import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { assert } from "chai";
import { Keypair, LAMPORTS_PER_SOL, PublicKey, Connection } from "@solana/web3.js";
import { TokenManager } from "../sdk/typescript/src/tokenManager";
import { ComplianceClient, KycStatus } from "../sdk/typescript/src/complianceClient";
import { ComplianceRegistry } from "../target/types/compliance_registry"; // Generated by 'anchor build'
import { getAssociatedTokenAddress } from "@solana/spl-token";

// --- CONFIGURATION ---
const COMPLIANCE_PROGRAM_ID = new PublicKey("COMPLYb623W7w5vT5Vv2k737Mh4W9p1m5sK8C47A7A7A"); // **REPLACE WITH YOUR DEPLOYED PROGRAM ID**
const TOKEN_DECIMALS = 6;
const TOKEN_AMOUNT = 100 * Math.pow(10, TOKEN_DECIMALS); 

// --- KEYPAIRS ---
// The Anchor workspace handles the 'provider' and 'program' setup automatically.
const provider = anchor.AnchorProvider.env();
anchor.setProvider(provider);
const program = anchor.workspace.ComplianceRegistry as Program<ComplianceRegistry>;

// Wallets for testing
const payer = provider.wallet as anchor.Wallet;
const issuerAuthority = payer.publicKey; // The wallet that initializes the mint and KYC
const permanentDelegate = payer.publicKey; // For simplicity, same as issuer
const userAlice = Keypair.generate(); 
const userBob = Keypair.generate(); 

describe("solana-kyc-compliance-sdk INTEGRATION TEST", () => {
    let mintPubKey: PublicKey;
    let tokenManager: TokenManager;
    let complianceClient: ComplianceClient;

    before(async () => {
        // Initialize supporting clients
        tokenManager = new TokenManager(provider.connection, payer.keypair, COMPLIANCE_PROGRAM_ID);
        complianceClient = new ComplianceClient(provider.connection, payer, COMPLIANCE_PROGRAM_ID);
        
        // Fund test users
        await provider.connection.requestAirdrop(userAlice.publicKey, 10 * LAMPORTS_PER_SOL);
        await provider.connection.requestAirdrop(userBob.publicKey, 10 * LAMPORTS_PER_SOL);
        
        // 1. CREATE COMPLIANT MINT (TokenManager)
        console.log("1. Creating compliant Token-2022 Mint with Transfer Hook...");
        mintPubKey = await tokenManager.createCompliantMint(
            issuerAuthority, // Mint Authority
            permanentDelegate, // Permanent Delegate
            TOKEN_DECIMALS
        );
        
        // 2. INITIALIZE EAML (Instructions)
        const [eamlPda] = complianceClient.getExtraAccountMetaListPda(mintPubKey);
        console.log("2. Initializing Extra Account Meta List (EAML)...");
        await program.methods
            .initializeExtraAccountMetaList()
            .accounts({
                payer: issuerAuthority,
                mint: mintPubKey,
                extraAccountMetaList: eamlPda,
                token2022Program: TOKEN_2022_PROGRAM_ID,
                systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();

        // 3. MINT TO ALICE (TokenManager)
        console.log(`3. Minting ${TOKEN_AMOUNT / Math.pow(10, TOKEN_DECIMALS)} tokens to Alice...`);
        await tokenManager.mintToWallet(
            mintPubKey,
            userAlice.publicKey,
            BigInt(TOKEN_AMOUNT),
            payer.keypair, // Mint Authority sign
            TOKEN_DECIMALS
        );
    });

    // --- TEST 1: Transfer Fails Without KYC ---
    it("Should FAIL a transfer when recipient has no KYC status (Transfer Hook fails)", async () => {
        const aliceAta = await getAssociatedTokenAddress(mintPubKey, userAlice.publicKey, false, TOKEN_2022_PROGRAM_ID);
        const bobAta = await getAssociatedTokenAddress(mintPubKey, userBob.publicKey, false, TOKEN_2022_PROGRAM_ID);

        try {
            // Attempt to transfer from Alice to Bob
            await anchor.spl.token.transfer(
                provider, 
                userAlice, // Signer for the source account owner
                aliceAta, 
                bobAta, 
                userAlice.publicKey, // Authority
                TOKEN_AMOUNT / 2, // Half the tokens
                [], // Extra accounts are resolved by EAML
                TOKEN_2022_PROGRAM_ID
            );
            // If the transfer succeeds, the test should fail
            assert.fail("Transfer should have failed due to missing KYC status.");
        } catch (error: any) {
            // The Transfer Hook should cause a Transaction Failed error
            console.log(`Expected Error: ${error.logs ? error.logs.pop() : error.message}`);
            assert.include(error.message, "Transaction failed", "Expected transaction failure");
            // NOTE: Check your program logs for the exact error code (e.g., ComplianceError::DestinationWalletNotCompliant)
        }
    });

    // --- TEST 2: Set KYC Status ---
    it("Should successfully set KYC status for Alice and Bob (ComplianceClient)", async () => {
        // Set an expiration date far in the future (e.g., 1 year from now)
        const ONE_YEAR_IN_SECONDS = 365 * 24 * 60 * 60;
        const validUntil = Math.floor(Date.now() / 1000) + ONE_YEAR_IN_SECONDS;
        
        // Initialize and set status for both users
        await complianceClient.initializeKycStatus(userAlice.publicKey, validUntil);
        await complianceClient.initializeKycStatus(userBob.publicKey, validUntil);

        // Verify status was written
        const aliceStatus = await complianceClient.getComplianceStatus(userAlice.publicKey);
        const bobStatus = await complianceClient.getComplianceStatus(userBob.publicKey);

        assert.equal(aliceStatus?.status, "Approved", "Alice's status should be Approved.");
        assert.equal(bobStatus?.status, "Approved", "Bob's status should be Approved.");
    });
    
    // --- TEST 3: Transfer Succeeds With KYC ---
    it("Should SUCCEED transfer after both wallets are KYC compliant", async () => {
        const aliceAta = await getAssociatedTokenAddress(mintPubKey, userAlice.publicKey, false, TOKEN_2022_PROGRAM_ID);
        const bobAta = await getAssociatedTokenAddress(mintPubKey, userBob.publicKey, false, TOKEN_2022_PROGRAM_ID);
        const transferAmount = TOKEN_AMOUNT / 4; 

        // Get initial balances
        const initialAliceBalance = (await provider.connection.getTokenAccountBalance(aliceAta)).value.amount;

        // Perform the transfer from Alice to Bob
        await anchor.spl.token.transfer(
            provider, 
            userAlice, // Signer
            aliceAta, 
            bobAta, 
            userAlice.publicKey, 
            transferAmount, 
            [], 
            TOKEN_2022_PROGRAM_ID
        );

        // Verify balances changed
        const finalAliceBalance = (await provider.connection.getTokenAccountBalance(aliceAta)).value.amount;
        const finalBobBalance = (await provider.connection.getTokenAccountBalance(bobAta)).value.amount;

        assert.equal(
            Number(finalAliceBalance), 
            Number(initialAliceBalance) - transferAmount, 
            "Alice's balance should decrease."
        );
        assert.equal(
            Number(finalBobBalance), 
            transferAmount, 
            "Bob's balance should receive the transfer amount."
        );
    });
});
